const $=s=>document.querySelector(s);
let matches=[], limit=30, configured=false;
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(date,options)=>new Intl.DateTimeFormat('en-GB',{timeZone:'Europe/London',...options}).format(new Date(date));
const dateKey=m=>m.kickoff?fmt(m.kickoff,{year:'numeric',month:'2-digit',day:'2-digit'}):'TBC';
function filtered(){const q=$('#search').value.trim().toLowerCase(),gw=$('#gameweek').value;return matches.filter(m=>(gw==='all'||String(m.gameweek)===gw)&&(!q||`${m.home.name} ${m.away.name}`.toLowerCase().includes(q)));}
function form(team){return `<div class="form" aria-label="Recent form: ${team.recent.map(g=>g.result).join(', ')||'Unavailable'}">${team.recent.map(g=>`<b class="${g.result}">${g.result}</b>`).join('')}</div>`;}
function team(t){return `<div><img class="crest" src="https://resources.premierleague.com/premierleague/badges/t${Number(t.code)}.svg" alt="" loading="lazy"><div class="team-name">${escape(t.name)}</div>${form(t)}</div>`;}
function card(m){const p=m.prediction;const winner=p?(p.outcome==='draw'?'Draw':`${m[p.outcome].name} win`):'';
return `<article class="card" id="match-${m.id}" aria-label="${escape(m.home.name)} versus ${escape(m.away.name)}"><div class="card-top"><span class="gw">GAMEWEEK ${m.gameweek??'TBC'}</span><span>${m.kickoff?fmt(m.kickoff,{hour:'2-digit',minute:'2-digit'}):'Time TBC'}${m.provisional?' · provisional':''}</span></div><div class="teams">${team(m.home)}<div><div class="score ${p?'':'waiting'}">${p?p.score.join(' : '):'VS'}</div><div class="score-caption">${p?'JEV PREDICTION':'KICK-OFF'}</div></div>${team(m.away)}</div><div class="prediction">${p?`<div class="prediction-heading"><span>✦ JEV’S PICK</span><strong>${escape(winner)}</strong></div><div class="prob-bar" aria-hidden="true">${['home','draw','away'].map(k=>`<span data-weight="${p.probabilities[k]}"></span>`).join('')}</div><div class="prob-labels"><span>${escape(m.home.short)} ${Math.round(p.probabilities.home*100)}%</span><span>Draw ${Math.round(p.probabilities.draw*100)}%</span><span>${escape(m.away.short)} ${Math.round(p.probabilities.away*100)}%</span></div>`:`<div class="prediction-heading"><span>✦ A FRESH PERSPECTIVE</span><span>Jev AI</span></div><p class="prediction-pending">${configured?'Jev predicts this fixture once its gameweek is next up.':'Add an AI Gateway key to the server to enable predictions.'}</p>`}</div></article>`;}
function render(){const all=filtered(),visible=all.slice(0,limit);$('#shown-count').textContent=all.length;
const groups=new Map();for(const m of visible){const key=dateKey(m);if(!groups.has(key))groups.set(key,[]);groups.get(key).push(m);}
$('#matches').innerHTML=visible.length?[...groups.values()].map(group=>`<div class="date-heading">${group[0].kickoff?fmt(group[0].kickoff,{weekday:'long',day:'numeric',month:'long',year:'numeric'}):'Date to be confirmed'}<span>${group.length} ${group.length===1?'match':'matches'}</span></div><div class="cards">${group.map(card).join('')}</div>`).join(''):'<div class="empty">No upcoming fixtures match this selection.</div>';document.querySelectorAll('[data-weight]').forEach(el=>el.style.setProperty('--weight',el.dataset.weight));$('#load-more').hidden=visible.length>=all.length;}
function notice(text,error=false){$('#notice').textContent=text;$('#notice').classList.toggle('error',error);}
async function request(url){const r=await fetch(url);const data=await r.json();if(!r.ok)throw new Error(data.error||'Request failed. Please retry.');return data;}
async function load(){$('#refresh').disabled=true;notice('Fetching official Premier League fixtures…');try{const d=await request('/api/fixtures');matches=d.matches;configured=d.configured;const previous=$('#gameweek').value;$('#gameweek').innerHTML='<option value="all">All gameweeks</option>'+[...new Set(matches.map(m=>m.gameweek).filter(x=>x!=null))].sort((a,b)=>a-b).map(g=>`<option value="${g}">Gameweek ${g}</option>`).join('');$('#gameweek').value=[...$('#gameweek').options].some(x=>x.value===previous)?previous:'all';$('#fixture-count').textContent=matches.length;$('#updated').textContent=`Updated ${fmt(d.updatedAt,{hour:'2-digit',minute:'2-digit'})} · ${fmt(d.updatedAt,{day:'numeric',month:'short'})}`;const firstDate=matches.find(m=>m.kickoff)?.kickoff;if(firstDate){const date=new Date(firstDate),year=date.getUTCFullYear()-(date.getUTCMonth()<6?1:0);$('#season').textContent=`${year}/${String(year+1).slice(-2)} SEASON`;}render();notice(configured?'Official fixtures · Jev predicts the next gameweek automatically, once a day.':'Add your AI Gateway key to the server’s environment to enable predictions.',!configured);}catch(e){notice(e.message,true);if(!matches.length)$('#matches').innerHTML='<div class="empty">Fixtures are unavailable right now. Use Refresh to try again.</div>';}finally{$('#refresh').disabled=false;}}
function resultRow(r){const p=r.prediction,picked=p.outcome==='draw'?'a draw':`${r[p.outcome].name} win`;return `<article class="result-row"><div class="result-teams"><span>${escape(r.home.name)}</span><span class="result-score">${r.actualScore.join(' : ')}</span><span>${escape(r.away.name)}</span></div><div class="result-meta"><span class="result-predicted">Jev picked ${escape(picked)} · ${p.score.join(':')}</span><span class="badge ${r.correctOutcome?'badge-correct':'badge-wrong'}">${r.correctOutcome?'✓':'✗'} outcome</span><span class="badge ${r.correctScore?'badge-correct':'badge-wrong'}">${r.correctScore?'✓':'✗'} exact score</span></div></article>`;}
async function loadResults(){try{const d=await request('/api/results');const s=d.summary;$('#tr-resolved').textContent=s.resolved;$('#tr-outcome').textContent=s.resolved?`${Math.round(s.outcomeAccuracy*100)}%`:'—';$('#tr-score').textContent=s.resolved?`${Math.round(s.scoreAccuracy*100)}%`:'—';$('#track-list').innerHTML=d.results.length?d.results.map(resultRow).join(''):'<div class="empty">No fixtures have finished yet this season.</div>';$('#track-notice').textContent=s.resolved?`${s.outcomeCorrect} of ${s.resolved} outcomes correct · ${s.scoreCorrect} exact scores.`:'Jev hasn’t had any predicted fixtures finish yet.';}catch(e){$('#track-notice').textContent=e.message;$('#track-notice').classList.add('error');}}
$('#gameweek').addEventListener('change',()=>{limit=30;render();});$('#search').addEventListener('input',()=>{limit=30;render();});$('#load-more').addEventListener('click',()=>{limit+=30;render();});$('#refresh').addEventListener('click',()=>load());
load();loadResults();
